import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Avion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <div
            style={{ transition: "0.5s" }}
            className="light:bg-slate-100 dark:bg-[#0F1625] transition"
          >
            <Header />
            <main className="mt-40">{children}</main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
